### ISSUE TITLE
Update link to Shiny extension for VS Code

### ISSUE THREAD

**Issue by gadenbuie** [youngroklee-ml/mastering-shiny-for-python#9]
Just a note to let you know that we've renamed the "Shiny for Python extension for VS Code" to the "Shiny extension for VS Code". In the process, we've moved the extension from `Posit.shiny-python` to `Posit.shiny`.

The new link is <https://marketplace.visualstudio.com/items?itemName=posit.shiny>.

https://github.com/youngroklee-ml/mastering-shiny-for-python/blob/72062afcd539a26694781ae99433f8ec56a2d131/action-workflow.qmd#L29

**Comment by youngroklee-ml** [comment]
Thank you very much for letting me know. I will update the link!
